# Generated by Django 6.0 on 2026-02-10 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowchart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('type', models.CharField(choices=[('flowchart', 'Flowchart'), ('sequence', 'Sequence'), ('gantt', 'Gantt'), ('class', 'Class'), ('git', 'Git'), ('er', 'ER'), ('journey', 'Journey'), ('quadrant', 'Quadrant'), ('xy', 'XY')], help_text='Type of flowchart to generate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowcharts', to='chat.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session'], name='chat_flowch_session_884146_idx'), models.Index(fields=['created_at'], name='chat_flowch_created_544d86_idx')],
            },
        ),
    ]
