# Generated by Django 6.0 on 2026-02-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_chunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
    ]
