# Generated by Django 6.0 on 2026-02-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_alter_chunk_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
